Update jar-file_springbootdeploymentmedichain.yml

diff --git a/.github/workflows/jar-file_springbootdeploymentmedichain.yml b/.github/workflows/jar-file_springbootdeploymentmedichain.yml
--- a/.github/workflows/jar-file_springbootdeploymentmedichain.yml
+++ b/.github/workflows/jar-file_springbootdeploymentmedichain.yml
@@ -1,12 +1,9 @@
-# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
-# More GitHub Actions for Azure: https://github.com/Azure/actions
-
 name: Build and deploy JAR app to Azure Web App - SpringbootDeploymentMediChain
 
 on:
   push:
     branches:
-      - JAR-FILE
+      - JARANDXML
   workflow_dispatch:
 
 jobs:
@@ -24,11 +21,20 @@ jobs:
       - name: Build with Maven
         run: mvn clean install
 
+      - name: Verify required files are present
+        run: |
+          if [[ ! -f target/*.jar ]] || [[ ! -f pom.xml ]]; then
+            echo "Missing required files for deployment"
+            exit 1
+          fi
+
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v2
         with:
           name: java-app
-          path: '${{ github.workspace }}/target/*.jar'
+          path: |
+            target/*.jar
+            pom.xml
 
   deploy:
     runs-on: windows-latest
